name: WILDARK
version: '1.0'
main: me.harpervenom.wildark.WILDARK
api-version: '1.21.3'
commands:
  m:
    description: Личная информация
    usage: "/m"
  setdayduration:
    usage: "/setdayduration <duration_in_ticks>"
