name: WILDARK
version: '1.0'
main: me.harpervenom.wildark.WILDARK
api-version: '1.21.3'
commands:
  help:
    description: Информация о сервере
    usage: "/help"
  m:
    description: Личная информация
    usage: "/m"
  setdayduration:
    usage: "/setdayduration <duration_in_ticks>"
  grant:
    description: Выдать права к участку другому игроку
    usage: "/grant <player> <region name> <relation>"
  delete:
    description: Удалить свой участок
    usageg: "/delete <region name>"